### Recuperar todas las recetas
GET http://localhost:3000/recetas

### Recuperar una receta por ID
GET http://localhost:3000/recetas/678f2c6dbe39fda40af74bcf

### Actualizar una receta
PUT http://localhost:3000/recetas/678f2c6dbe39fda40af74bd4
Content-Type: application/json

{
  "estado": "aprobada"
}

### Crear una receta con POST
POST http://localhost:3000/recetas
Content-Type: application/json

{
  "titulo": "Tarta de Manzana",
  "descripcion": "Una deliciosa tarta de manzana con canela.",
  "ingredientes": ["3 manzanas", "1 taza de harina", "1 cucharadita de canela"],
  "preparacion": "1. Pelar y cortar las manzanas...",
  "autor": "64f1a2b3c8e9f0a1b2c3d4e5",
  "estado": "pendiente"
}
### Eliminar una receta
DELETE http://localhost:3000/recetas/6794700e72cd9c3558271061

### Subir una imagen para una receta
POST http://localhost:3000/recetas/678f2c6dbe39fda40af74bd3/upload-imagen
Content-Type: application/json

{
  "imageUrl": "https://www.doritos.com/sites/doritos.com/files/doritos-cool-ranch-bacon-nachos-v2.jpg"
}
### Obtener una imagen por su nombre
GET http://localhost:3000/obtener-imagen/nombre_de_la_imagen.jpg

### Obtener todos los usuarios
GET http://localhost:3000/users

### Obtener un usuario por ID
GET http://localhost:3000/users/678f2bc6be39fda40af74bd1

### Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "Lissette Flores",
  "email": "aso@papasfritas.com",
  "contraseña": "hashedpassword4",
  "rol": "usuario"
}

### Iniciar sesión (éxito)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "juan@papasfritas.com",
  "contraseña": "hashedpassword3"
}

### Iniciar sesión (credenciales incorrectas)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "juan@papasfritas.com",
  "contraseña": "contraseñaIncorrecta"
}

### Iniciar sesión (campos faltantes)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "juan@papasfritas.com"
}

### Crear un nuevo usuario (campos faltantes)
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "Pamela Flores",
  "email": "juan@papasfritas.com"
}

### Crear un nuevo usuario (email duplicado)
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "Pamela Flores",
  "email": "juan@papasfritas.com",
  "contraseña": "hashedpassword3",
  "rol": "usuario"
}